# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d0ea41d565a2c948ab7049c56c7f7a0a428525896e237e9febbabfe1fb3c99d07a9596e989f8918d70aae834829fa5a748b5b35897974ecc62864ebd901778f

test:
  secret_key_base: 76c8defb447403eecf22f35923a836b3defd12170ba0929efce32ff8de6ec65a1f8470d7eb2a42b99ea547094f8504403d9e8d9665e4ec4c799e3b7370feab8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
